version: '3.1'

services:
  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0-alpine

  web:
    build: .
    environment:
      SERVER_NAME: localhost:8000
      SECRET_KEY: qwerty
      DATABASE_URL: postgres://postgres:secret@database:5432/postgres
      REDIS_URL: redis://redis:6379/0
    command: >
      sh -c "python manage.py db upgrade
      && python manage.py serve -h 0.0.0.0"
    volumes:
      - .:/app
    depends_on:
      - database
      - redis
    ports:
      - 8000:8000

  worker:
    build: .
    environment:
      SERVER_NAME: localhost:8000
      SECRET_KEY: qwerty
      DATABASE_URL: postgres://postgres:secret@database:5432/postgres
      REDIS_URL: redis://redis:6379/0
    command: >
      sh -c "python manage.py db upgrade
      && python manage.py tasks"
    volumes:
      - .:/app
    depends_on:
      - database
      - redis
